---

- name: add gitlab package signing key
  apt_key: id=E15E78F4 url=https://packages.gitlab.com/gpg.key

- name: install gitlab repository
  apt_repository: repo='deb https://packages.gitlab.com/gitlab/gitlab-ce/debian jessie main'

- name: install gitlab
  package: name=gitlab-ce state=latest

- name: write gitlab configuration file
  template: src=gitlab.rb.j2 dest=/etc/gitlab/gitlab.rb owner=root group=root mode=0600
  notify:
    - reconfigure gitlab

- name: write gitlab secrets file
  template: src=gitlab-secrets.json.j2 dest=/etc/gitlab/gitlab-secrets.json owner=root group=root mode=0600
  notify:
    - reconfigure gitlab
