---

- name: refresh apt cache
  apt: update_cache=yes

- name: install common packages
  package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - vim

- name: remove common packages
  package: name={{ item }} state=absent
  with_items:
    - puppet
    - puppet-common
