---

- name: refresh apt cache
  apt:
    update_cache: yes
    cache_valid_time: '3600'

- name: enable jessie-backports
  apt_repository:
    repo: deb http://debian.csail.mit.edu/debian/ jessie-backports main
    state: present
  when: "{{ common_enable_backports }}"

- name: install common packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"
