---

- name: add plex package signing key
  apt_key:
    id: 3ADCA79D
    url: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: install plex repository
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb/ public main

- name: install plex
  package:
    name: plexmediaserver
    state: latest

- name: install java for filebot
  apt:
    name: default-jre
    state: latest
    default_release: jessie-backports

- name: install filebot
  apt:
    deb: https://app.filebot.net/download.php?type=deb&arch=amd64&version=4.7.7
