---

- name: add docker package signing key
  apt_key:
    id: 2C52609D
    url: https://yum.dockerproject.org/gpg

- name: install docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo/ {{ ansible_lsb.id|lower }}-jessie main

- name: install docker
  package:
    name: docker-engine=1.12.6-0~{{ ansible_lsb.id|lower }}-jessie
    state: present
